# Generated by Django 5.0.6 on 2024-06-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
