# Generated by Django 5.0.6 on 2024-06-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_alter_dish_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
