# Generated by Django 5.0.6 on 2024-06-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0003_dish_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='dish_images/'),
        ),
    ]
