# Generated by Django 5.0.6 on 2024-06-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0004_alter_dish_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='image_url',
            new_name='image',
        ),
    ]
